name: Demo Develocity Injection

on:
  push:
  workflow_dispatch:

env:
  DEVELOCITY_ACCESS_KEY: ${{secrets.DEVELOCITY_ACCESS_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Inject Develocity
      run: |
        mkdir -p .mvn
        cp -n .github/resources/.mvn/extensions.xml .mvn/extensions.xml
        cp -n .github/resources/.mvn/develocity.xml .mvn/develocity.xml

    - name: Setup Maven
      uses: gradle/develocity-actions/maven-setup@ff50eedf5eedbbcb8f1f7308c80b5dea9e0f7ca5

    - name: Build with Maven
      run: mvn -X -B package --file pom.xml
